SHOW CREATE table  sqldados.oprd;
SHOW CREATE table  sqldados.ords;

TRUNCATE TABLE oprdPendente;
TRUNCATE TABLE ordsPendente;


CREATE TABLE `oprdPendente` (
  `date` int(10) NOT NULL DEFAULT '0',
  `ordno` int(10) NOT NULL DEFAULT '0',
  `mult` int(10) NOT NULL DEFAULT '0',
  `ipi` int(10) NOT NULL DEFAULT '0',
  `freight` int(10) NOT NULL DEFAULT '0',
  `icms` int(10) NOT NULL DEFAULT '0',
  `auxLong1` int(10) NOT NULL DEFAULT '0',
  `auxLong2` int(10) NOT NULL DEFAULT '0',
  `auxMy1` bigint(15) NOT NULL DEFAULT '0',
  `auxMy2` bigint(15) NOT NULL DEFAULT '0',
  `icmsSubst` int(10) NOT NULL DEFAULT '0',
  `auxLong3` int(10) NOT NULL DEFAULT '0',
  `auxLong4` int(10) NOT NULL DEFAULT '0',
  `auxMy3` bigint(15) NOT NULL DEFAULT '0',
  `auxMy4` bigint(15) NOT NULL DEFAULT '0',
  `qtty` double DEFAULT NULL,
  `qtty_src` double DEFAULT NULL,
  `qtty_xfr` double DEFAULT NULL,
  `cost` double DEFAULT NULL,
  `qttyRcv` double DEFAULT NULL,
  `qttyCancel` double DEFAULT NULL,
  `qttyVendaMes` double DEFAULT NULL,
  `qttyVendaMesAnt` double DEFAULT NULL,
  `qttyVendaMedia` double DEFAULT NULL,
  `qttyPendente` double DEFAULT NULL,
  `stkDisponivel` double DEFAULT NULL,
  `qttyAbc` double DEFAULT NULL,
  `storeno` smallint(5) NOT NULL DEFAULT '0',
  `seqno` smallint(5) NOT NULL DEFAULT '0',
  `status` smallint(5) NOT NULL DEFAULT '0',
  `bits` smallint(5) NOT NULL DEFAULT '0',
  `bits2` smallint(5) NOT NULL DEFAULT '0',
  `auxShort1` smallint(5) NOT NULL DEFAULT '0',
  `auxShort2` smallint(5) NOT NULL DEFAULT '0',
  `auxShort3` smallint(5) NOT NULL DEFAULT '0',
  `auxShort4` smallint(5) NOT NULL DEFAULT '0',
  `prdno` char(16) NOT NULL DEFAULT '',
  `grade` char(8) NOT NULL DEFAULT '',
  `remarks` char(36) NOT NULL DEFAULT '',
  `padbyte` char(2) NOT NULL DEFAULT '',
  `gradeFechada` char(4) NOT NULL DEFAULT '',
  `obs` char(40) NOT NULL DEFAULT '',
  `auxStr` char(40) NOT NULL DEFAULT '',
  PRIMARY KEY (`storeno`,`ordno`,`prdno`,`grade`,`seqno`),
  KEY `i2` (`storeno`,`ordno`),
  KEY `i3` (`prdno`,`grade`),
  KEY `i4` (`storeno`,`ordno`,`seqno`),
  KEY `i5` (`ordno`,`status`,`storeno`,`prdno`,`grade`),
  KEY `i6` (`ordno`,`prdno`,`grade`,`remarks`,`storeno`),
  KEY `i7` (`storeno`,`ordno`,`prdno`,`gradeFechada`,`grade`),
  KEY `i8` (`status`,`storeno`,`ordno`,`prdno`,`grade`),
  KEY `i9` (`storeno`,`ordno`,`auxStr`),
  KEY `i10` (`storeno`,`status`,`prdno`,`grade`),
  KEY `i11` (`storeno`,`prdno`,`grade`, date)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ordsPendente` (
  `no` int(10) NOT NULL DEFAULT '0',
  `date` int(10) NOT NULL DEFAULT '0',
  `vendno` int(10) NOT NULL,
  `discount` bigint(15) NOT NULL DEFAULT '0',
  `amt` bigint(15) NOT NULL DEFAULT '0',
  `package` bigint(15) NOT NULL DEFAULT '0',
  `custo_fin` bigint(15) NOT NULL DEFAULT '0',
  `others` bigint(15) NOT NULL DEFAULT '0',
  `eord_ordno` int(10) NOT NULL DEFAULT '0',
  `dataFaturamento` int(10) NOT NULL DEFAULT '0',
  `invno` int(10) NOT NULL DEFAULT '0',
  `freightAmt` bigint(15) NOT NULL DEFAULT '0',
  `auxLong1` int(10) NOT NULL DEFAULT '0',
  `auxLong2` int(10) NOT NULL DEFAULT '0',
  `amtOrigem` bigint(15) NOT NULL DEFAULT '0',
  `dataEntrega` int(10) NOT NULL DEFAULT '0',
  `discountOrig` bigint(15) NOT NULL,
  `l1` int(10) NOT NULL,
  `l2` int(10) NOT NULL,
  `l3` int(10) NOT NULL,
  `l4` int(10) NOT NULL,
  `m1` bigint(15) NOT NULL,
  `m2` bigint(15) NOT NULL,
  `m3` bigint(15) NOT NULL,
  `m4` bigint(15) NOT NULL,
  `deliv` smallint(5) NOT NULL DEFAULT '0',
  `storeno` smallint(5) NOT NULL DEFAULT '0',
  `carrno` smallint(5) NOT NULL DEFAULT '0',
  `empno` smallint(5) NOT NULL DEFAULT '0',
  `prazo` char(60) NOT NULL DEFAULT 'S12',
  `eord_storeno` smallint(5) NOT NULL DEFAULT '0',
  `delivOriginal` smallint(5) NOT NULL DEFAULT '0',
  `bits` smallint(5) NOT NULL DEFAULT '0',
  `bits2` smallint(5) NOT NULL DEFAULT '0',
  `bits3` smallint(5) NOT NULL,
  `padbyte` smallint(5) NOT NULL DEFAULT '0',
  `indxno` smallint(5) NOT NULL DEFAULT '0',
  `repno` smallint(5) NOT NULL DEFAULT '0',
  `auxShort1` smallint(5) NOT NULL DEFAULT '0',
  `auxShort2` smallint(5) NOT NULL DEFAULT '0',
  `noofinst` smallint(5) NOT NULL DEFAULT '0',
  `status` smallint(5) NOT NULL DEFAULT '0',
  `s1` smallint(5) NOT NULL,
  `s2` smallint(5) NOT NULL,
  `s3` smallint(5) NOT NULL,
  `s4` smallint(5) NOT NULL,
  `frete` char(40) NOT NULL DEFAULT '',
  `remarks` char(36) NOT NULL DEFAULT '',
  `ordnoFromVend` char(16) NOT NULL DEFAULT '',
  `remarksInv` char(240) NOT NULL DEFAULT '',
  `remarksRcv` char(240) NOT NULL DEFAULT '',
  `remarksOrd` char(240) NOT NULL DEFAULT '',
  `auxChar` char(40) NOT NULL DEFAULT '',
  `c1` char(40) NOT NULL,
  `c2` char(40) NOT NULL,
  `c3` char(40) NOT NULL,
  `c4` char(40) NOT NULL,
  PRIMARY KEY (`storeno`,`no`, date),
  KEY `i2` (`vendno`,`date`),
  KEY `i3` (`storeno`),
  KEY `i4` (`no`,`storeno`),
  KEY `i5` (`empno`,`no`,`storeno`),
  KEY `i6` (`vendno`,`dataFaturamento`),
  KEY `i7` (`storeno`,`date`),
  KEY `i8` (`storeno`,`dataFaturamento`),
  KEY `i9` (`storeno`,`dataEntrega`),
  KEY `i10` (`status`,`vendno`,`date`),
  KEY `i11` (`storeno`,`ordnoFromVend`),
  KEY `i12` (`storeno`,`vendno`,`date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

